"""
backend/graph_service.py — Neo4j driver wrapper.

Responsibilities:
  - Open/close Neo4j driver.
  - Execute predefined Cypher queries with parameters.
  - Return raw list[dict] results.

LLM does NOT touch this layer.
"""

from __future__ import annotations
from typing import Any

from neo4j import GraphDatabase, Driver, Record
from neo4j.exceptions import ServiceUnavailable, AuthError

import backend.config as config


class GraphService:
    """Thin wrapper around the Neo4j Python driver."""

    def __init__(self) -> None:
        self._driver: Driver | None = None

    # ------------------------------------------------------------------
    # Connection lifecycle
    # ------------------------------------------------------------------

    def connect(self) -> None:
        """Open driver connection (call once at startup)."""
        self._driver = GraphDatabase.driver(
            config.NEO4J_URI,
            auth=(config.NEO4J_USER, config.NEO4J_PASSWORD),
            notifications_disabled_categories=["UNRECOGNIZED"],
        )
        try:
            self._driver.verify_connectivity()
        except ServiceUnavailable as exc:
            raise ConnectionError(
                f"Cannot reach Neo4j at {config.NEO4J_URI}: {exc}"
            ) from exc
        except AuthError as exc:
            raise PermissionError(
                f"Neo4j authentication failed for user '{config.NEO4J_USER}': {exc}"
            ) from exc

    def close(self) -> None:
        """Close the driver connection."""
        if self._driver:
            self._driver.close()
            self._driver = None

    def __enter__(self) -> "GraphService":
        self.connect()
        return self

    def __exit__(self, *_: Any) -> None:
        self.close()

    # ------------------------------------------------------------------
    # Query execution
    # ------------------------------------------------------------------

    def run_query(
        self,
        cypher: str,
        parameters: dict[str, Any] | None = None,
    ) -> list[dict[str, Any]]:
        """
        Execute a predefined Cypher query and return a plain list of dicts.

        Parameters
        ----------
        cypher:
            The exact Cypher query string (from retrieval_scenarios.py).
            NEVER generated by the LLM — always hardcoded.
        parameters:
            Optional Cypher parameters ($param_name → value).

        Returns
        -------
        list[dict]
            Each element is one result row, with Neo4j values converted to
            Python primitives (str, int, float, bool, list, dict, None).
        """
        if self._driver is None:
            raise RuntimeError("GraphService not connected. Call connect() first.")

        params: dict[str, Any] = parameters or {}

        with self._driver.session(database=config.NEO4J_DATABASE) as session:
            result = session.run(cypher, params)
            rows: list[dict[str, Any]] = []
            for record in result:
                rows.append(_record_to_dict(record))
            return rows


# ---------------------------------------------------------------------------
# Private helpers
# ---------------------------------------------------------------------------

def _record_to_dict(record: Record) -> dict[str, Any]:
    """
    Recursively convert a Neo4j Record (which may contain Node, Relationship,
    Path, or primitive values) to a plain Python dict.
    """
    row: dict[str, Any] = {}
    for key in record.keys():
        row[key] = _convert(record[key])
    return row


def _convert(value: Any) -> Any:
    """Recursively convert Neo4j driver types to JSON-serialisable primitives."""
    from neo4j.graph import Node, Relationship, Path

    if value is None:
        return None
    if isinstance(value, (bool, int, float, str)):
        return value
    if isinstance(value, list):
        return [_convert(v) for v in value]
    if isinstance(value, dict):
        return {k: _convert(v) for k, v in value.items()}
    if isinstance(value, Node):
        props = dict(value.items())
        return {k: _convert(v) for k, v in props.items()}
    if isinstance(value, Relationship):
        props = dict(value.items())
        return {k: _convert(v) for k, v in props.items()}
    if isinstance(value, Path):
        nodes = [_convert(n) for n in value.nodes]
        return nodes
    return str(value)
